apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m6h3cnhx2-python 
  janus-idp.io/tekton: m6h3cnhx2-python
  backstage.io/kubernetes-id: m6h3cnhx2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m6h3cnhx2-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  